window.GW_PLACES={
ubud:[['tegalalang','Tegallalang Rice Terrace','RICE TERRACES · LANDSCAPE','Walk the famous layered rice fields north of Ubud and give the landscape more time than a photo stop.','90–120 min'],['saraswati','Saraswati Temple','TEMPLE · ARCHITECTURE','A central Ubud temple known for its lotus pond and an easy cultural stop between town walks.','30–60 min'],['campuhan','Campuhan Ridge Walk','WALK · NATURE','A green ridge walk best used as a slower counterpoint to Ubud’s busy center.','60–90 min']],
uluwatu:[['uluwatu-temple','Uluwatu Temple','TEMPLE · CLIFFS · SUNSET','A Balinese sea temple set high above the Indian Ocean, strongest when paired with the cliff setting.','90–120 min'],['padang-padang','Padang Padang Beach','BEACH · SURF','A compact cove and surf beach that works well as one stop in a southern Bali day.','1–2 hr'],['suluban','Suluban Beach','BEACH · CAVES · SURF','A dramatic approach through rock formations to one of the Bukit Peninsula’s distinctive surf breaks.','1–2 hr']],
seminyak:[['seminyak-beach','Seminyak Beach','BEACH · SUNSET','The neighborhood’s natural anchor: broad sand, surf and an easy transition into sunset and dinner.','1–3 hr'],['petitenget-temple','Petitenget Temple','TEMPLE · CULTURE','A historic temple close to the resort strip that adds cultural context to a beach-heavy day.','30–45 min'],['eat-street','Kayu Aya / Eat Street','FOOD · WALK','A useful dining-and-wandering spine through Seminyak rather than a single restaurant recommendation.','1–2 hr']],
nusapenida:[['kelingking','Kelingking Beach Viewpoint','VIEWPOINT · COAST','Nusa Penida’s signature cliff view; the viewpoint itself can be the goal without forcing the difficult descent.','60–90 min'],['broken-beach','Broken Beach','COAST · GEOLOGY','A natural rock arch and circular cove that pairs naturally with nearby Angel’s Billabong.','45–75 min'],['crystal-bay','Crystal Bay','BEACH · SNORKEL','A west-coast beach suited to swimming or snorkeling when sea conditions cooperate.','1–2 hr']],
hotelzone:[['playa-forum','Playa Forum','BEACH · CENTRAL','A lively public beach in the heart of Cancún’s Hotel Zone with easy access to the surrounding strip.','1–2 hr'],['museo-maya','Museo Maya de Cancún','MUSEUM · MAYA HISTORY','A museum and archaeological site that gives a resort-heavy Cancún stay much-needed historical context.','1–2 hr'],['el-rey','El Rey Archaeological Zone','ARCHAEOLOGY · HISTORY','Compact Maya ruins inside the Hotel Zone, easy to combine with a beach day.','45–75 min']],
playadelfines:[['delfines-beach','Playa Delfines','BEACH · FREE','Wide public sand and Caribbean color without needing to enter a resort.','1–3 hr'],['cancun-sign','Cancún Sign at Playa Delfines','VIEWPOINT · PHOTO','A quick landmark stop best folded into time already being spent at Playa Delfines.','10–20 min'],['san-miguelito','San Miguelito Archaeological Site','ARCHAEOLOGY · CULTURE','Maya remains adjoining Museo Maya, useful for adding history to the southern Hotel Zone.','45–75 min']],
islamujeres:[['playa-norte','Playa Norte','BEACH · SWIM','The island’s best-known beach, valued for shallow turquoise water and an easy town-adjacent location.','2–3 hr'],['punta-sur','Punta Sur','CLIFFS · SCULPTURE · VIEW','The island’s dramatic southern tip with coastal views and a very different mood from Playa Norte.','60–90 min'],['centro-isla','Isla Mujeres Centro','STREETS · FOOD · LOCAL','Walk the compact town grid around Hidalgo rather than seeing the island only from a golf cart.','1–2 hr']],
yucatan:[['chichen-itza','Chichén Itzá','MAYA HERITAGE · UNESCO','A major Maya archaeological complex that deserves to be the anchor of the day, not one rushed stop among many.','2–3 hr'],['cenote-ik-kil','Cenote Ik Kil','CENOTE · SWIM','A dramatic open-air cenote often paired with Chichén Itzá; timing matters if you want a calmer swim.','1–2 hr'],['valladolid','Valladolid Centro','COLONIAL TOWN · FOOD','A colorful Yucatán town that can turn a transfer day into a more rounded cultural route.','2–3 hr']],
southbeach:[['south-pointe-park','South Pointe Park','FREE · WATERFRONT · SUNSET','Promenade, pier, beach access and big views at the quieter southern end of South Beach.','60–120 min'],['art-deco-district','Art Deco Historic District','ARCHITECTURE · WALK','Walk Ocean Drive and the surrounding blocks slowly enough to notice the architecture behind the neon.','60–90 min'],['lincoln-road','Lincoln Road','PEDESTRIAN · FOOD · SHOPS','A pedestrian stretch for people-watching, cafés and an easy break from the beach.','1–2 hr']],
wynwood:[['wynwood-walls','Wynwood Walls','STREET ART · CULTURE','A concentrated introduction to large-scale street art before exploring the wider neighborhood.','60–90 min'],['museum-graffiti','Museum of Graffiti','MUSEUM · STREET ART','A focused museum that adds history and context to the murals outside.','60–90 min'],['wynwood-marketplace','Wynwood Marketplace','FOOD · SOCIAL','An outdoor food-and-social stop that works best as part of a wider Wynwood wander.','1–2 hr']],
littlehavana:[['domino-park','Domino Park','CULTURE · PEOPLE-WATCHING','A small but meaningful Calle Ocho stop where the neighborhood’s social rhythm is visible.','20–40 min'],['cuban-memorial','Cuban Memorial Boulevard','HISTORY · WALK','A short walk that adds historical context beyond food and souvenir stops.','30–45 min'],['tower-theater','Tower Theater','CINEMA · HERITAGE','An Art Deco-era landmark at the heart of Calle Ocho and a useful orientation point for the neighborhood.','20–40 min']],
brickell:[['brickell-city-centre','Brickell City Centre','ARCHITECTURE · SHOPS · FOOD','A large urban complex that shows the polished, contemporary side of Brickell.','1–2 hr'],['brickell-key','Brickell Key Walk','WATERFRONT · WALK','A calmer waterfront loop with skyline views just off the dense tower district.','45–75 min'],['miami-circle','Miami Circle','HISTORY · WATERFRONT','A small archaeological and waterfront site that hints at Miami history beneath the modern skyline.','30–45 min']],
westminster:[['westminster-abbey','Westminster Abbey','HISTORY · ARCHITECTURE','One of London’s defining historic interiors; give it enough time to absorb the detail rather than only seeing the façade.','1.5–2 hr'],['parliament-square','Parliament Square + Big Ben','LANDMARK · FREE','A compact cluster of iconic London views that works best early or toward evening.','30–60 min'],['st-james-park','St James’s Park','PARK · WALK · FREE','A green link between Westminster and the royal sights that makes the route itself enjoyable.','45–75 min']],
southbank:[['southbank-centre','Southbank Centre','CULTURE · RIVER','A major arts complex and natural anchor for a Thames-side walking day.','1–2 hr'],['london-eye','London Eye','VIEW · LANDMARK','A 30-minute observation-wheel rotation with broad central London views; booking timing matters.','45–75 min'],['tate-modern','Tate Modern','ART · FREE COLLECTION','A major modern-art museum farther east along the river, ideal as the cultural anchor of a South Bank walk.','1.5–3 hr']],
coventgarden:[['covent-garden-market','Covent Garden Market','MARKET · ARCHITECTURE','The famous market halls and piazza are busiest at peak times, but still worth seeing as the neighborhood’s center.','45–90 min'],['royal-opera-house','Royal Ballet and Opera','PERFORMANCE · ARCHITECTURE','A landmark performance venue that can turn a Covent Garden wander into an evening plan.','2–3 hr'],['seven-dials','Seven Dials','STREETS · SHOPS · FOOD','Seven converging streets with independent shops and food, useful for wandering beyond the main piazza.','45–90 min']],
camden:[['camden-market','Camden Market','MARKET · FOOD · SHOPS','A sprawling market complex where browsing and eating are the point; arrive with time rather than a checklist.','2–3 hr'],['regents-canal-camden','Regent’s Canal at Camden Lock','CANAL · WALK · FREE','Use the towpath to escape the busiest market streets and see a different side of Camden.','45–90 min'],['roundhouse','Roundhouse','MUSIC · VENUE','A historic circular performance venue closely tied to Camden’s live-music identity.','1–3 hr']],
northgoa:[['fort-aguada','Fort Aguada','FORT · COAST · HISTORY','A Portuguese-era fort and coastal viewpoint that adds history to a North Goa beach circuit.','60–90 min'],['vagator-beach','Vagator Beach','BEACH · CLIFFS','A scenic North Goa beach with a different feel from the denser Calangute–Baga stretch.','1–3 hr'],['anjuna-flea','Anjuna Market Area','MARKET · SHOPPING','A classic North Goa browsing stop; market activity varies by day and season, so verify before going.','1–2 hr']],
southgoa:[['palolem-beach','Palolem Beach','BEACH · BAY','A palm-backed crescent in the far south, good for a slower beach day when conditions are suitable.','2–4 hr'],['colva-beach','Colva Beach','BEACH · WALK','A long South Goa beach that works well for an uncomplicated sand-and-walk day.','1–3 hr'],['cabo-de-rama','Cabo de Rama Fort','FORT · CLIFFS · VIEW','A dramatic coastal fort where the setting and views are as important as the ruins.','1–2 hr']],
oldgoa:[['bom-jesus','Basilica of Bom Jesus','UNESCO · CHURCH · HISTORY','A major Old Goa monument housing the remains of St Francis Xavier and an essential stop in the heritage complex.','45–75 min'],['se-cathedral','Sé Cathedral','CHURCH · ARCHITECTURE','A monumental cathedral facing the Old Goa heritage lawns, naturally paired with Bom Jesus.','30–60 min'],['christian-art-museum','Museum of Christian Art','MUSEUM · INDO-PORTUGUESE ART','A focused collection that adds depth to the churches by showing the artistic exchange behind Goan Christian heritage.','60–90 min']],
goainterior:[['dudhsagar','Dudhsagar Falls','WATERFALL · NATURE','A major waterfall excursion where access changes with season and conditions; plan transport rather than improvising.','Half day+'],['tambdi-surla','Tambdi Surla Mahadev Temple','TEMPLE · FOREST','A historic stone temple in a forested setting that rewards travelers willing to go inland.','1–2 hr'],['spice-plantation','Ponda Spice Plantation Area','FOOD · AGRICULTURE','Use a reputable plantation visit to understand the crops and food traditions behind Goa’s greener interior.','2–3 hr']],
oldmontreal:[['notre-dame-montreal','Notre-Dame Basilica','BASILICA · ARCHITECTURE','A defining Old Montréal interior on Place d’Armes and a strong anchor for the historic district.','60–90 min'],['pointe-a-calliere','Pointe-à-Callière','MUSEUM · ARCHAEOLOGY','Montréal’s archaeology and history museum, especially useful for understanding what lies beneath the old city.','1.5–2.5 hr'],['saint-paul-street','Saint-Paul Street','HISTORIC STREET · WALK','One of the easiest ways to experience Old Montréal at street level: stone façades, galleries and side streets.','45–90 min']],
plateau:[['parc-la-fontaine','Parc La Fontaine','PARK · LOCAL · FREE','A large neighborhood park that shows the Plateau at everyday speed rather than as a sightseeing checklist.','60–90 min'],['avenue-mont-royal','Avenue du Mont-Royal','STREET · FOOD · SHOPS','A major Plateau spine for cafés, shops and people-watching; sections are pedestrianized seasonally.','1–2 hr'],['square-saint-louis','Square Saint-Louis','PARK · ARCHITECTURE','A compact leafy square surrounded by colorful historic homes and an easy starting point for side-street wandering.','30–60 min']],
mileend:[['st-viateur','St-Viateur Bagel','FOOD · MONTRÉAL CLASSIC','One of Mile End’s landmark bagel bakeries; treat it as a quick food stop within a wider neighborhood walk.','20–40 min'],['fairmount-bagel','Fairmount Bagel','FOOD · MONTRÉAL CLASSIC','Another long-running Mile End bagel institution, useful for the inevitable side-by-side comparison.','20–40 min'],['drawn-quarter','Bernard + St-Laurent Walk','CAFÉS · SHOPS · STREETS','Use the streets between Bernard, St-Laurent and the surrounding blocks as the real attraction rather than chasing one pin.','1–2 hr']],
mountroyal:[['kondiaronk','Kondiaronk Belvedere','VIEWPOINT · FREE','The classic Montréal skyline lookout near the Mount Royal Chalet.','45–75 min'],['beaver-lake','Beaver Lake','PARK · WALK · FAMILY','A relaxed green-space stop on the mountain, useful for families and slower park time.','60–90 min'],['mount-royal-trails','Mount Royal Trails','WALK · NATURE · FREE','Forest paths that make the climb part of the experience instead of treating the lookout as the only goal.','1–2 hr']]
};
window.GW_AREA_META={ubud:['Bali','Ubud'],uluwatu:['Bali','Uluwatu'],seminyak:['Bali','Seminyak'],nusapenida:['Bali','Nusa Penida'],hotelzone:['Cancún','Hotel Zone'],playadelfines:['Cancún','Playa Delfines'],islamujeres:['Cancún','Isla Mujeres'],yucatan:['Cancún','Yucatán'],southbeach:['Miami','South Beach'],wynwood:['Miami','Wynwood'],littlehavana:['Miami','Little Havana'],brickell:['Miami','Brickell'],westminster:['London','Westminster'],southbank:['London','South Bank'],coventgarden:['London','Covent Garden'],camden:['London','Camden'],northgoa:['Goa','North Goa'],southgoa:['Goa','South Goa'],oldgoa:['Goa','Old Goa'],goainterior:['Goa','Goa interior'],oldmontreal:['Montréal','Old Montréal'],plateau:['Montréal','Plateau Mont-Royal'],mileend:['Montréal','Mile End'],mountroyal:['Montréal','Mount Royal']};
window.GW_CITY_SLUG={'Bali':'bali','Cancún':'cancun','Miami':'miami','London':'london','Goa':'goa','Montréal':'montreal'};
window.GW_CITY_IMG={'Bali':'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1800&q=88','Cancún':'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?auto=format&fit=crop&w=1800&q=88','Miami':'https://images.unsplash.com/photo-1535498730771-e735b998cd64?auto=format&fit=crop&w=1800&q=88','London':'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1800&q=88','Goa':'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1800&q=88','Montréal':'https://images.unsplash.com/photo-1519178614-68673b201f36?auto=format&fit=crop&w=1800&q=88'};